export const CREATE_TERM_SUCCESS = "CREATE_TERM_SUCCESS";
export const CREATE_TERM_REQUEST = "CREATE_TERM_REQUEST";
export const CREATE_TERM_FAIL = "CREATE_TERM_FAIL";

export const ADD_COURSE = 'ADD_COURSE';